### ISSUE TITLE
MP3 issue

### ISSUE THREAD

**Issue by anferbui** [HPCE/hpce-2015-cw2#1]
Just a minor issue, the MP3 file mentioned in 'Checking it works' doesn't seem to exist (or we don't have permission to access it).

URL of the file is:
http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/bn9th_m4.mp3

Error code: 403

**Comment by m8pple** [comment]
Yup, my bad. I managed to mis-configure just after testing.

It should be working now (with curl or wget). Please re-open if
its not (it worked for me from home).

**Comment by gaochangw** [comment]
I still can't get access to it.
