### ISSUE TITLE
.libs/libsox.lax/libgsm.a: No such file or directory

### ISSUE THREAD

**Issue by aaronsheah** [HPCE/hpce-2015-cw2#2]
Occurs in the **Building the Code** section. Command line will throw Error 1 when 'make' is entered. Below is the output

../libtool: line 1090: cd: .libs/libsox.lax/libgsm.a: No such file or directory
make[1]: **\* [libsox.la] Error 1
make: **\* [all-recursive] Error 1

System : Mac OS X 10.11

**Comment by m8pple** [comment]
Ah, the dreaded Mac. This is a bit of a moving target year-to-year.

So some questions:
- Does the file/directory `.libs/libsox.lax/libgsm.a` exist?
- Are there any errors occurring further up the build, that are 
  stopping this happening?
- Could you attach a file with a log of the build?
- Is it possible to build lame (using the same instructions), or
  do you get the same error?

**Comment by aaronsheah** [comment]
A classmate asked suggested to change my folder names to a name without spaces and everything worked fine.
