### ISSUE TITLE
Failing to build lame

### ISSUE THREAD

**Issue by mazei513** [HPCE/hpce-2015-cw2#3]
Trying to build Lame just as we did with sox, however am facing an error while building it after 'make' command.

> In file included from lametime.c:125:0:
> lametime.c: In function ‘lame_set_stream_binary_mode’:
> lametime.c:139:25: error: ‘_O_BINARY’ undeclared (first use in this function)
>      setmode(fileno(fp), _O_BINARY);
>                          ^
> lametime.c:139:25: note: each undeclared identifier is reported only once for each function it appears in
> Makefile:392: recipe for target 'lametime.o' failed
> make[2]: **\* [lametime.o] Error 1
> make[2]: Leaving directory '/cygdrive/c/(folder path here)/hpce-2015-cw2/build/lame-3.99.5/frontend'
> Makefile:349: recipe for target 'all-recursive' failed
> make[1]: **\* [all-recursive] Error 1
> make[1]: Leaving directory '/cygdrive/c/(folder path here)/hpce-2015-cw2/build/lame-3.99.5'
> Makefile:276: recipe for target 'all' failed
> make: **\* [all] Error 2

I've looked at Issue #2 and have avoided having spaces in my folder names. I have also tried as noted to configure with 'CPPFLAGS=-march=native' but still getting the same error. Using 'make clean' does not give the error, while 'make install' ends up with the same error.

Used cygwin on Windows 10 Pro 64-bit.

**Comment by m8pple** [comment]
Umm, _O_BINARY is related to doing raw IO... from memory it occurs
when #including conio.h or something, so I think it is one of the
strange not-quite-posix things that windows sticks an underscore
on the front of (normally it is O_BINARY).

Slight guess: are you using cygwin 64-bit? My suspicion
is that this is LAME not understanding that 64-bit cygwin is not
windows.

If you're using 64-bit cygwin, would you mind trying with a 32-bit cygwin?
You should be able to keep the 64-bit version in-place and install
the 32-bit version alongside while testing.

(That said, I _thought_ it was working in cygwin64 - this may be due
to compiler upgrades or windows SDK changes or something).

**Comment by emadkhan2k** [comment]
Same issue here. I tried using the 32-bit cygwin instead and it still gives the same error:

> lametime.c: In function ‘lame_set_stream_binary_mode’:
> lametime.c:139:25: error: ‘_O_BINARY’ undeclared (first use in this function)
>     setmode(fileno(fp), _O_BINARY);
>                         ^
> lametime.c:139:25: note: each undeclared identifier is reported only once for each function it appears in
> Makefile:392: recipe for target 'lametime.o' failed
> make[2]: **\* [lametime.o] Error 1
> make[2]: Leaving directory '/cygdrive/c/users/emad/Documents/GitHub/hpce-2015-cw2/build/lame-3.99.5/frontend'
> Makefile:349: recipe for target 'all-recursive' failed
> make[1]: **\* [all-recursive] Error 1
> make[1]: Leaving directory '/cygdrive/c/users/emad/Documents/GitHub/hpce-2015-cw2/build/lame-3.99.5'
> Makefile:276: recipe for target 'all' failed
> make: **\* [all] Error 2

Looking at the "lametime.c" file and locating the line which causes the error. 

> #elif defined **CYGWIN**
>    setmode(fileno(fp), _O_BINARY);

It seems that the script is correctly identifying the system as cygwin and not windows?

I am using 32-bit cygwin on 64-bit Windows 10. Here are some details about my setup:

> $ uname -a
> CYGWIN_NT-6.1-WOW Emad-Laptop 2.2.1(0.289/5/3) 2015-08-20 11:40 i686 Cygwin
> 
> $ make -v
> GNU Make 4.1
> Built for i686-pc-cygwin
> 
> $ gcc --version
> gcc (GCC) 4.9.3

**Comment by m8pple** [comment]
I'm looking into this now, when I try to compile on my cygwin32 it works fine,
but on cygwin64 I can reproduce the same error.

I'm trying to compile from scratch with a clean cygwin32, and should be able
to produce a patch that sorts it out.

**Comment by m8pple** [comment]
I've put together a corrected package at:
http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/lame-3.99.5-alt.tar.gz

I've tested this in:
- cygwin64
- cygwin32
- Ubuntu 14
- Ubuntu 12

Can you check if that works for you? If so, I'll replace the current
package with this one.

**Comment by emadkhan2k** [comment]
The new package now builds without any errors on cygwin64 for me. Thanks.

**Comment by howchanghong** [comment]
Had the same issue. The new package works perfectly.
