### ISSUE TITLE
Incorrect use of $ when getting relative directory

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2015-cw2#4]
Somebody pointed out (sorry, I've forgotten who), that there is a problem in the
instructions for getting the relative directory. What I've suggested is doing this:

```
./configure --prefix="$(pwd)/../../local"
```

This works fine in the shell, but what I didn't consider is what happens inside
the makefile.

Inside the makefile, `$` means "macro expansion", and `$(X)` means look
for makefile variable called X. I managed to introduce this bug as  a
[regression](https://en.wikipedia.org/wiki/Software_regression) in this commit: d43cbb6e5c4fb0fa3ffe50a3919d7572db2f7c9e. The aim was to make things simpler, but I didn't test properly.

Potential solutions are:
## Use back-tick syntax

In the shell, the syntax:

```
`pwd`
```

is equivalent to

```
$(pwd)
```

so you can use:

```
./configure --prefix="`pwd`/../../local"
```

in the makefile or on the command line.
## Use shell from within the makefile

There is a function called `shell` in makefiles which will
call a function in the shell. So this:

```
$(shell pwd)
```

will work within the makefile. However, it will _not_ work on
the shell. So in the makefile you can use something like:

```
./configure --prefix="$(shell pwd)/../../local"
```
## Use the abspath function in the makefile

There is also a function called abspath within make, which uses
an internal function (not the shell) to get an absolute path. You
can used this as something like:

```
$(abspath ../../local)
```

to get the path of a file. So the makefile command becomes:

```
./configure --prefix="$(abspath ../../local)"
```

**Comment by cianyleow** [comment]
@m8pple your help file on the slightly nicer version of the command has an extra ')' at the end before the double quotes.

**Comment by SzeKiatTan** [comment]
I used $(CURDIR) and it seems to work in the makefile. Just wondering if it is a legitimate usage?

**Comment by m8pple** [comment]
Yes, you're right CURDIR works too. In fact it's probably a
better solution than my suggestions when working in the
makefile. I'll note it in the main readme.
