### ISSUE TITLE
Cygwin build of lame-3.99.5, error in lametime.c

### ISSUE THREAD

**Issue by ghost** [HPCE/hpce-2015-cw2#6]
Hello everyone,

I have just noticed that when using cygwin, the compilation of the lame-3.99.5 source code fails because of an issue in lametime.c (\frontend\lametime.c).
You need to comment the two lines (line 138 to 139):
/*
# elif defined **CYGWIN**

```
setmode(fileno(fp), _O_BINARY);
```

*/
This is quite annoying for writing the makefiles, is there any chance the tar file hosted could be modified with this change?

Thanks !

**Comment by m8pple** [comment]
I've moved the modified tar file from issue #3 over the original. It seems that it is not
causing anyone any problems.

So now both files point to the same place:
- http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/lame-3.99.5.tar.gz
- http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/lame-3.99.5-alt.tar.gz

I don't mind which people use in their submitted makefile.

**Comment by ghost** [comment]
Sorry I did not noticed the closed issue 3. Everything seems to work now, thanks a lot !
